import type { StudioKnowledgeItem } from "../types/models";

// Generated by scripts/import-napkin-rag.mjs from Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0.
// Re-run the importer when the external RAG package changes.
export const importedStudioKnowledgeItems: StudioKnowledgeItem[] = [
  {
    "id": "napkin-audio:radio-production-standards:core",
    "title": "Radio Ad Production Standards",
    "topic": "radio_production_standards",
    "productionStage": [
      "master",
      "export"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social"
    ],
    "summary": "Practical, citation-backed guidance for radio ad production standards in Napkin Audio AI Studio.",
    "guidance": [
      "Radio advertising masters should be treated as short-form broadcast programmes rather than as music masters.",
      "The safest workflow is to set the destination first, meter using an ITU-R BS.1770-compliant loudness meter, preserve true-peak headroom, and export a high-quality source master before making any compressed delivery copies .",
      "EBU R 128 is the key European reference for programme loudness, recommending an average programme loudness of -23 LUFS and descriptors for loudness range and maximum true peak .",
      "Use 48 kHz, 24-bit WAV as the internal production and archive master unless a broadcaster asks for another format.",
      "For podcast and digital variants, create separate derivatives rather than reusing a crushed broadcast file."
    ],
    "keywords": [
      "ad",
      "audio production",
      "napkin audio",
      "production",
      "radio",
      "radio ad production standards",
      "radio ads",
      "radio-production-standards",
      "stards",
      "radio-production",
      "producer-assistant",
      "radio_production_standards",
      "What LUFS should I master a UK radio ad to?",
      "What file format should I export for podcast ads?",
      "How do I make a final master broadcast-safe?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/radio-production-standards/radio-production-standards.md. Sources: https://www.itu.int/rec/R-REC-BS.1770, https://tech.ebu.ch/publications/r128, https://podcasters.apple.com/support/893-audio-requirements, https://support.spotify.com/us/artists/article/loudness-normalization/, https://aes.org/audio-topics/loudness-2/, https://www.rtw.com/blog/rtw-knowledge-base-1/worldwide-loudness-delivery-standards-4",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:mixing-mastering:core",
    "title": "Audio Mixing And Mastering",
    "topic": "mixing_mastering",
    "productionStage": [
      "mix",
      "master"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "music",
      "sfx"
    ],
    "summary": "Practical, citation-backed guidance for audio mixing and mastering in Napkin Audio AI Studio.",
    "guidance": [
      "The mix exists to protect the spoken idea.",
      "In a radio ad, music and sound design earn their place only when they improve comprehension, emotion, or recall.",
      "The voice-over should be stable enough that listeners do not need to adjust playback volume, while the bed should feel present rather than obviously ducked.",
      "Start by editing breaths, mouth clicks, obvious noise, and performance problems before using heavy processing.",
      "A high-pass filter commonly removes rumble below roughly 80–100 Hz, while muddiness often sits around 200–500 Hz, presence around 3–5 kHz, and air around 10–15 kHz ."
    ],
    "keywords": [
      "audio",
      "audio mixing and mastering",
      "audio production",
      "mastering",
      "mixing",
      "mixing-mastering",
      "napkin audio",
      "radio ads",
      "radio-production",
      "producer-assistant",
      "mixing_mastering",
      "My music bed is overpowering the VO, what should I do?",
      "How do I de-ess a harsh voiceover?",
      "How should I check a radio mix on phones and cars?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/mixing-mastering/mixing-mastering.md. Sources: https://www.itu.int/rec/R-REC-BS.1770, https://www.izotope.com/en/learn/the-dos-and-donts-of-de-essing.html, https://www.izotope.com/en/learn/how-to-eq-vocals.html, https://www.voice123.com/blog/marketing-trends-tactics/how-to-mix-music-and-voice-over-for-maximum-impact/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:script-timing:core",
    "title": "Script Timing And Copy Editing",
    "topic": "script_timing",
    "productionStage": [
      "script",
      "recording"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "dubbing"
    ],
    "summary": "Practical, citation-backed guidance for script timing and copy editing in Napkin Audio AI Studio.",
    "guidance": [
      "Script timing is a performance problem, not just a word-count problem.",
      "A word-count table gives an early warning, but real timing must be checked by reading aloud at the intended emotion, pace, and disclaimer speed.",
      "Voice-over timing calculators are useful planning tools , and industry voice-over guidance places typical spoken delivery around 125–150 WPM, with style, emphasis, pauses, and complexity changing the result .",
      "| Duration | Safe range | Normal retail range | Risk point | |---:|---:|---:|---| | 10 seconds | 18–24 words | 22–27 words | More than one message.",
      "| | 15 seconds | 30–38 words | 35–42 words | Weak CTA or rushed brand."
    ],
    "keywords": [
      "audio production",
      "copy",
      "editing",
      "napkin audio",
      "radio ads",
      "script",
      "script timing and copy editing",
      "script-timing",
      "timing",
      "radio-production",
      "producer-assistant",
      "script_timing",
      "Is this 30 second radio script too long?",
      "How many words fit in a 15 second ad?",
      "Rewrite this script to fit 20 seconds."
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/script-timing/script-timing.md. Sources: https://edgestudio.com/words-to-time-calculator/, https://www.provoiceactor.co.uk/blog/words-to-time/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:copywriting-strategy:core",
    "title": "Radio Copywriting And Creative Strategy",
    "topic": "copywriting_strategy",
    "productionStage": [
      "brief",
      "script",
      "compliance"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social"
    ],
    "summary": "Practical, citation-backed guidance for radio copywriting and creative strategy in Napkin Audio AI Studio.",
    "guidance": [
      "A strong radio ad is clear after one listen.",
      "The listener cannot reread the copy, so structure must do the work: arrest attention, identify the brand or situation, deliver one useful reason to care, and close with a concrete action.",
      "| Structure | Best use | Shape | |---|---|---| | Offer-led | Retail, events, limited-time promotions | Problem or reveal, offer, proof, deadline CTA.",
      "| | Brand-led | Awareness and positioning | Distinctive world, brand truth, memorable sonic device.",
      "| | Dialogue | Demonstration or comedy | Conflict, twist, product resolution, brand button."
    ],
    "keywords": [
      "audio production",
      "copywriting",
      "copywriting-strategy",
      "creative",
      "napkin audio",
      "radio",
      "radio ads",
      "radio copywriting and creative strategy",
      "strategy",
      "radio-production",
      "producer-assistant",
      "copywriting_strategy",
      "How do I write a radio ad that is clear after one listen?",
      "Give me a better ending for this retail ad.",
      "What structure should a testimonial radio ad use?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/copywriting-strategy/copywriting-strategy.md. Sources: https://www.asa.org.uk/codes-and-rulings/advertising-codes/broadcast-code.html, https://adstandards.ie/asa-code/, https://www.radiocentre.org/clearance/fast-track-trustmark/, https://www.provoiceactor.co.uk/blog/words-to-time/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:voice-casting:core",
    "title": "Voice Casting And Voice Direction",
    "topic": "voice_casting",
    "productionStage": [
      "casting",
      "recording"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "dubbing"
    ],
    "summary": "Practical, citation-backed guidance for voice casting and voice direction in Napkin Audio AI Studio.",
    "guidance": [
      "Voice casting is brand strategy made audible.",
      "Match the voice to the audience, product risk, price point, and emotional task.",
      "A voice can add trust, speed, local familiarity, luxury, mischief, or authority, but it cannot repair a confused script.",
      "| Criterion | Producer question | Example choice | |---|---|---| | Brand posture | Is the brand close, expert, rebellious, or premium?",
      "| Warm local voice for community trust."
    ],
    "keywords": [
      "audio production",
      "casting",
      "direction",
      "napkin audio",
      "radio ads",
      "voice",
      "voice casting and voice direction",
      "voice-casting",
      "radio-production",
      "producer-assistant",
      "voice_casting",
      "What voice style fits a premium finance ad?",
      "How should I direct an Irish local retail VO?",
      "Should this script use one voice or two?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/voice-casting/voice-casting.md. Sources: https://elevenlabs.io/docs/product-guides/playground/text-to-speech, https://elevenlabs.io/docs/product-guides/voices/voice-design",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:elevenlabs-ai-voice:core",
    "title": "ElevenLabs And AI Voice Workflow",
    "topic": "elevenlabs_ai_voice",
    "productionStage": [
      "casting",
      "recording"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "dubbing"
    ],
    "summary": "Practical, citation-backed guidance for elevenlabs and ai voice workflow in Napkin Audio AI Studio.",
    "guidance": [
      "AI voice production should be treated like a casting, directing, and comping workflow.",
      "Generate options, compare against the brief, and keep only takes that sound intentional.",
      "ElevenLabs notes that voice selection, source quality, model choice, and settings all affect output, and that the system is nondeterministic .",
      "Prepare clean copy with pronunciation hints, punctuation, and paragraph breaks.",
      "Choose a voice that already carries the desired tone; do not expect settings to turn a cheerful voice into a premium authority voice."
    ],
    "keywords": [
      "ai",
      "audio production",
      "elevenlabs",
      "elevenlabs and ai voice workflow",
      "elevenlabs-ai-voice",
      "napkin audio",
      "radio ads",
      "voice",
      "workflow",
      "radio-production",
      "producer-assistant",
      "elevenlabs_ai_voice",
      "Why does my ElevenLabs voice sound flat?",
      "What stability setting should I start with?",
      "How do I prompt an AI voice for a soft Irish accent?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/elevenlabs-ai-voice/elevenlabs-ai-voice.md. Sources: https://elevenlabs.io/docs/product-guides/playground/text-to-speech, https://elevenlabs.io/docs/product-guides/voices/voice-design, https://elevenlabs.io/safety",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:sound-design-sfx:core",
    "title": "Sound Design And SFX",
    "topic": "sound_design_sfx",
    "productionStage": [
      "sound_design",
      "mix"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "sfx"
    ],
    "summary": "Practical, citation-backed guidance for sound design and sfx in Napkin Audio AI Studio.",
    "guidance": [
      "Sound design should make the listener see the ad.",
      "In radio, a single well-chosen sound can establish location, product, scale, or comedy faster than explanatory copy.",
      "The danger is clutter: every effect competes with speech for attention.",
      "Start with the script and mark the beats: opening world, product proof, transition, reveal, CTA, and logo.",
      "Add SFX only where they change meaning or memory."
    ],
    "keywords": [
      "audio production",
      "design",
      "napkin audio",
      "radio ads",
      "sfx",
      "sound",
      "sound design and sfx",
      "sound-design-sfx",
      "radio-production",
      "producer-assistant",
      "sound_design_sfx",
      "Create an SFX cue sheet for this script.",
      "What sound effects suit a luxury car radio ad?",
      "How do I stop SFX cluttering the VO?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/sound-design-sfx/sound-design-sfx.md. Sources: https://www.voice123.com/blog/marketing-trends-tactics/how-to-mix-music-and-voice-over-for-maximum-impact/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:music-scoring:core",
    "title": "Music Beds And Scoring",
    "topic": "music_scoring",
    "productionStage": [
      "music",
      "mix"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "music"
    ],
    "summary": "Practical, citation-backed guidance for music beds and scoring in Napkin Audio AI Studio.",
    "guidance": [
      "The music bed sets pace and expectation before the listener fully processes the words.",
      "Choose music for message fit, not personal taste.",
      "Voice123 notes that music can amplify the message and suggests genre choices based on tone, such as cinematic for scale, corporate electronic for drive, ambient for calm, acoustic for empathy, and playful acoustic for comedy .",
      "| Need | Music direction | Producer warning | |---|---|---| | Urgency | 130–160 BPM, percussive build | Do not crush legal clarity.",
      "| | Premium | Sparse, confident, slower pulse | Avoid over-bright stock loops."
    ],
    "keywords": [
      "audio production",
      "beds",
      "music",
      "music beds and scoring",
      "music-scoring",
      "napkin audio",
      "radio ads",
      "scoring",
      "radio-production",
      "producer-assistant",
      "music_scoring",
      "What BPM should a retail sale bed use?",
      "Prompt an AI music bed for a 30 second premium ad.",
      "How should music end under a logo sting?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/music-scoring/music-scoring.md. Sources: https://www.voice123.com/blog/marketing-trends-tactics/how-to-mix-music-and-voice-over-for-maximum-impact/, https://support.spotify.com/us/artists/article/loudness-normalization/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:dubbing-localization:core",
    "title": "Dubbing And Localization",
    "topic": "dubbing_localization",
    "productionStage": [
      "script",
      "recording",
      "compliance"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "dubbing"
    ],
    "summary": "Practical, citation-backed guidance for dubbing and localization in Napkin Audio AI Studio.",
    "guidance": [
      "It is timed persuasion in another language.",
      "The localized version must preserve the offer, emotion, brand character, legal meaning, and duration, even when sentence structure changes.",
      "First, lock the source intent: what must the listener remember and do?",
      "Second, identify culturally specific phrases, prices, dates, pronunciations, and regulated claims.",
      "Third, translate for meaning and timing."
    ],
    "keywords": [
      "audio production",
      "dubbing",
      "dubbing and localization",
      "dubbing-localization",
      "localization",
      "napkin audio",
      "radio ads",
      "radio-production",
      "producer-assistant",
      "dubbing_localization",
      "Translate this ad without exceeding 30 seconds.",
      "How do I preserve tone in dubbing?",
      "What should I check in localized legal copy?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/dubbing-localization/dubbing-localization.md. Sources: https://elevenlabs.io/docs/product-guides/playground/text-to-speech, https://elevenlabs.io/docs/product-guides/voices/voice-design, https://elevenlabs.io/safety",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:compliance-risk:core",
    "title": "Compliance And Risk Awareness",
    "topic": "compliance_risk",
    "productionStage": [
      "script",
      "compliance",
      "export"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social"
    ],
    "summary": "Practical, citation-backed guidance for compliance and risk awareness in Napkin Audio AI Studio.",
    "guidance": [
      "The assistant must provide risk flags and review suggestions, not legal advice.",
      "UK broadcast advertising is governed by the BCAP Code, which covers areas such as misleading advertising, harm and offence, children, political matters, environmental claims, medicines, financial products, gambling, alcohol, competitions, and scheduling .",
      "In Ireland, the Advertising Standards Authority Code applies to commercial marketing communications across broadcast, print, digital, and promotions, and breaching communications must be withdrawn or amended .",
      "Coimisiún na Meán also makes media service codes and rules for broadcasters and on-demand services, including commercial communications and protection of audiences and children .",
      "| Category | Typical risk | Assistant action | |---|---|---| | Alcohol | Under-18 appeal, irresponsible consumption, health or success claims | Flag and recommend clearance/legal review."
    ],
    "keywords": [
      "audio production",
      "awareness",
      "compliance",
      "compliance and risk awareness",
      "compliance-risk",
      "napkin audio",
      "radio ads",
      "risk",
      "radio-production",
      "producer-assistant",
      "compliance_risk",
      "Does this alcohol radio ad need legal review?",
      "Flag compliance risks in this gambling ad.",
      "Can I make this environmental claim in UK radio?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/compliance-risk/compliance-risk.md. Sources: https://www.asa.org.uk/codes-and-rulings/advertising-codes/broadcast-code.html, https://adstandards.ie/asa-code/, https://www.cnam.ie/industry-and-professionals/complaints/broadcasting-on-demand/obligations/codes-rules/, https://www.nibusinessinfo.co.uk/content/cap-and-bcap-advertising-codes, https://www.radiocentre.org/clearance/fast-track-trustmark/, https://www.asa.org.uk/type/broadcast/code_section/31.html",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:sonic-branding:core",
    "title": "Sonic Branding",
    "topic": "sonic_branding",
    "productionStage": [
      "brief",
      "music",
      "sound_design",
      "mix"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "music",
      "sfx"
    ],
    "summary": "Practical, citation-backed guidance for sonic branding in Napkin Audio AI Studio.",
    "guidance": [
      "Sonic branding creates memory across multiple ads.",
      "It can be a jingle, mnemonic, logo sting, recurring voice, sound palette, rhythm, or production world.",
      "The test is whether the listener recognizes the brand before the spoken logo.",
      "| Component | Role | Production rule | |---|---|---| | Jingle | Name and message memory | Keep singable and legally clear.",
      "| | Mnemonic | Short recurring note pattern | Use consistently at brand moments."
    ],
    "keywords": [
      "audio production",
      "bring",
      "napkin audio",
      "radio ads",
      "sonic",
      "sonic branding",
      "sonic-branding",
      "radio-production",
      "producer-assistant",
      "sonic_branding",
      "Create sonic brand guidelines for this campaign.",
      "What is a mnemonic in radio advertising?",
      "How can I improve brand recall across ads?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/sonic-branding/sonic-branding.md. Sources: https://www.voice123.com/blog/marketing-trends-tactics/how-to-mix-music-and-voice-over-for-maximum-impact/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:producer-troubleshooting:core",
    "title": "Producer Assistant Troubleshooting",
    "topic": "producer_troubleshooting",
    "productionStage": [
      "brief",
      "script",
      "casting",
      "recording",
      "sound_design",
      "music",
      "mix",
      "master",
      "export",
      "compliance"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "dubbing",
      "music",
      "sfx"
    ],
    "summary": "Practical, citation-backed guidance for producer assistant troubleshooting in Napkin Audio AI Studio.",
    "guidance": [
      "A producer assistant should diagnose the production stage before suggesting a fix.",
      "Many issues sound like mix problems but are actually copy, casting, or music-selection problems.",
      "The assistant should ask what the listener needs to understand, then trace the failure backwards.",
      "| Symptom | Likely stage | First fix | |---|---|---| | Script too long | Script | Cut secondary claims before speeding VO.",
      "| | VO too quiet | Mix | Duck music and check low-volume playback."
    ],
    "keywords": [
      "assistant",
      "audio production",
      "napkin audio",
      "producer",
      "producer assistant troubleshooting",
      "producer-troubleshooting",
      "radio ads",
      "troubleshooting",
      "radio-production",
      "producer-assistant",
      "producer_troubleshooting",
      "The client says it does not sound premium, diagnose it.",
      "Why does my ad feel generic?",
      "What should I fix if the CTA is weak?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/producer-troubleshooting/producer-troubleshooting.md. Sources: https://www.itu.int/rec/R-REC-BS.1770, https://www.izotope.com/en/learn/the-dos-and-donts-of-de-essing.html, https://www.izotope.com/en/learn/how-to-eq-vocals.html, https://www.voice123.com/blog/marketing-trends-tactics/how-to-mix-music-and-voice-over-for-maximum-impact/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:studio-workflow:core",
    "title": "Studio Workflow SOPs",
    "topic": "studio_workflow",
    "productionStage": [
      "brief",
      "script",
      "casting",
      "recording",
      "sound_design",
      "music",
      "mix",
      "master",
      "export",
      "compliance"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "dubbing",
      "music",
      "sfx"
    ],
    "summary": "Practical, citation-backed guidance for studio workflow sops in Napkin Audio AI Studio.",
    "guidance": [
      "A repeatable studio workflow prevents creative quality from depending on memory.",
      "Each stage should create an artifact that can be inspected by humans and software agents: brief, script, timing report, casting notes, cue sheet, mix plan, compliance flags, export QA, and approval record.",
      "| Stage | Output | Gate | |---|---|---| | Brief intake | Brief summary and success metric | One listener action is clear.",
      "| | Script parsing | Claims, brand, CTA, legal, duration | Risk and timing issues flagged.",
      "| | Timing check | Word count and read-speed estimate | Fits with pauses and disclaimers."
    ],
    "keywords": [
      "audio production",
      "napkin audio",
      "radio ads",
      "sops",
      "studio",
      "studio workflow sops",
      "studio-workflow",
      "workflow",
      "radio-production",
      "producer-assistant",
      "studio_workflow",
      "Give me a step-by-step radio ad workflow.",
      "What artifacts should I create from brief to export?",
      "How should I manage client revisions?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/studio-workflow/studio-workflow.md. Sources: https://www.itu.int/rec/R-REC-BS.1770, https://www.asa.org.uk/codes-and-rulings/advertising-codes/broadcast-code.html, https://adstandards.ie/asa-code/, https://www.radiocentre.org/clearance/fast-track-trustmark/, https://elevenlabs.io/docs/product-guides/playground/text-to-speech, https://www.voice123.com/blog/marketing-trends-tactics/how-to-mix-music-and-voice-over-for-maximum-impact/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:client-feedback:core",
    "title": "Client Feedback Translation",
    "topic": "client_feedback",
    "productionStage": [
      "brief",
      "script",
      "casting",
      "sound_design",
      "music",
      "mix",
      "master"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social"
    ],
    "summary": "Practical, citation-backed guidance for client feedback translation in Napkin Audio AI Studio.",
    "guidance": [
      "Client feedback is often emotional shorthand.",
      "The producer assistant should translate vague phrases into testable production actions while avoiding defensive responses.",
      "Ask one clarifying question only when needed; otherwise propose a concrete plan.",
      "| Feedback | Likely production meaning | Action | |---|---|---| | Make it pop | More contrast, energy, or emphasis | Tighten hook, add lift, brighten key moment.",
      "| | More premium | Less hard-sell and more space | Slow VO, reduce claims, use sparse music."
    ],
    "keywords": [
      "audio production",
      "client",
      "client feedback translation",
      "client-feedback",
      "feedback",
      "napkin audio",
      "radio ads",
      "translation",
      "radio-production",
      "producer-assistant",
      "client_feedback",
      "What does make it pop mean in production terms?",
      "Translate client feedback into mix actions.",
      "How should I respond to too shouty?"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/client-feedback/client-feedback.md. Sources: https://www.izotope.com/en/learn/the-dos-and-donts-of-de-essing.html, https://www.izotope.com/en/learn/how-to-eq-vocals.html, https://www.voice123.com/blog/marketing-trends-tactics/how-to-mix-music-and-voice-over-for-maximum-impact/",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:prompt-templates:core",
    "title": "Prompt Templates",
    "topic": "prompt_templates",
    "productionStage": [
      "brief",
      "script",
      "casting",
      "recording",
      "sound_design",
      "music",
      "mix",
      "master",
      "export",
      "compliance"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social",
      "dubbing",
      "music",
      "sfx"
    ],
    "summary": "Practical, citation-backed guidance for prompt templates in Napkin Audio AI Studio.",
    "guidance": [
      "Prompts should specify role, input, constraints, output format, and quality checks.",
      "A useful production prompt produces work an editor can act on immediately.",
      "Rewrite this script for a {duration}-second {market} radio ad.",
      "Preserve the offer, brand, mandatory terms, and CTA.",
      "Output: revised script, estimated word count, removed claims, and risk flags.” “Reduce this script from {current_words} words to {target_words} words while preserving meaning."
    ],
    "keywords": [
      "audio production",
      "napkin audio",
      "prompt",
      "prompt templates",
      "prompt-templates",
      "radio ads",
      "templates",
      "radio-production",
      "producer-assistant",
      "prompt_templates",
      "Give me a prompt for script timing reduction.",
      "Create a mix diagnosis prompt.",
      "Create an ElevenLabs voice search prompt."
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: knowledge/prompt-templates/prompt-templates.md. Sources: https://elevenlabs.io/docs/product-guides/playground/text-to-speech, https://elevenlabs.io/docs/product-guides/voices/voice-design, https://elevenlabs.io/safety",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:ad_duration_word_count_table",
    "title": "Ad Duration Word Count Table",
    "topic": "ad_duration_word_count_table",
    "productionStage": [
      "script"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital"
    ],
    "summary": "Operational lookup table imported from tables/ad_duration_word_count_table.csv.",
    "guidance": [
      "10 | 20 | 23 | 27 | 18-24 | Use for IDs, stings, single-offer reminders, or one sharp retail line.",
      "15 | 30 | 35 | 40 | 30-38 | One idea, one proof point, one CTA. Avoid legal copy unless essential.",
      "20 | 40 | 47 | 53 | 40-50 | Allows a short setup plus offer; still needs disciplined pauses.",
      "30 | 60 | 70 | 80 | 65-75 | Standard spot length; reserve 2-4 seconds for brand and CTA.",
      "40 | 80 | 93 | 107 | 85-100 | Useful for dialogue or compliance-heavy retail. Keep scenes simple.",
      "60 | 120 | 140 | 160 | 125-145 | Best for storytelling, testimonials, or multi-proof brand ads."
    ],
    "keywords": [
      "ad duration word count table",
      "duration",
      "word count",
      "timing",
      "Ad Duration Word Count Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/ad_duration_word_count_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:loudness_export_targets_table",
    "title": "Loudness Export Targets Table",
    "topic": "loudness_export_targets_table",
    "productionStage": [
      "mix",
      "master",
      "export"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital",
      "social"
    ],
    "summary": "Operational lookup table imported from tables/loudness_export_targets_table.csv.",
    "guidance": [
      "European broadcast reference | -23 LUFS | -1 dBTP | 48 kHz | 24-bit preferred | WAV/BWF | EBU R128; ITU BS.1770 | Confirm station spec before delivery.",
      "US broadcast reference | -24 LKFS | -2 dBTP | 48 kHz | 24-bit preferred | WAV/BWF | RTW summary of ATSC A/85 | Use only when a US TV/radio-style spec requires it.",
      "Apple Podcasts | -16 LKFS ±1 dB | -1 dBFS true peak | 44.1/48 kHz | AAC or MP3 128-256 kbps stereo | AAC/MP3/WAV/FLAC | Apple Podcasts requirements | Precondition before encoding.",
      "Spotify music/streaming master | -14 LUFS | -1 dBTP, or -2 dBTP for louder masters | 44.1/48 kHz | High-quality stereo master | WAV/FLAC source | Spotify loudness normalization | Streaming normalization happens at playback.",
      "General online audio ad | -16 to -20 LUFS | -1 dBTP | 44.1/48 kHz | 16/24-bit WAV or 192-320 kbps MP3 | WAV/MP3 | AES/RTW streaming guidance | Prioritize intelligibility on phones and smart speakers.",
      "Social video/audio | -14 to -16 LUFS | -1 dBTP | 48 kHz | 24-bit WAV source, platform encode | WAV/MOV/MP4 audio | Platform-normalized practice | Keep mono compatibility and avoid brittle high end."
    ],
    "keywords": [
      "loudness export targets table",
      "loudness",
      "true peak",
      "export",
      "Loudness Export Targets Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/loudness_export_targets_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:mix_problem_diagnosis_table",
    "title": "Mix Problem Diagnosis Table",
    "topic": "mix_problem_diagnosis_table",
    "productionStage": [
      "mix"
    ],
    "appliesTo": [
      "radio",
      "podcast",
      "digital"
    ],
    "summary": "Operational lookup table imported from tables/mix_problem_diagnosis_table.csv.",
    "guidance": [
      "VO too quiet | Music/SFX mask speech or VO bus low | Listen at low volume on phone speaker | Raise VO 1-3 dB, duck music, carve music presence range | mix",
      "VO too harsh | Presence boost or sibilance excessive | Solo VO and check 3-8 kHz | Reduce narrow harsh bands, de-ess 4-10 kHz, soften limiter | mix",
      "VO too flat | AI stability too high or little dynamic contour | Compare against intended emotion | Regenerate with lower stability, add direction, vary punctuation | recording",
      "Music overpowering VO | Bed too loud or too dense | Mute SFX and check VO/music only | Lower bed under speech, automate ducking, choose sparser bed | music",
      "SFX too busy | Too many cues compete with copy | Play mono at low volume | Keep only story-critical cues and trim tails | sound_design",
      "Mix not broadcast-safe | Peak/loudness not checked | Run LUFS and true-peak meter | Normalize to required spec, limit ceiling, export WAV | master"
    ],
    "keywords": [
      "mix problem diagnosis table",
      "mix",
      "diagnosis",
      "music",
      "voice",
      "Mix Problem Diagnosis Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/mix_problem_diagnosis_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:voice_style_use_case_table",
    "title": "Voice Style Use Case Table",
    "topic": "voice_style_use_case_table",
    "productionStage": [
      "casting",
      "recording"
    ],
    "appliesTo": [
      "radio",
      "dubbing"
    ],
    "summary": "Operational lookup table imported from tables/voice_style_use_case_table.csv.",
    "guidance": [
      "warm conversational | local retail, healthcare, public service | natural, kind, close-mic, unforced | luxury with high status distance | Sound like a helpful neighbour, not an announcer.",
      "premium authority | finance, automotive, luxury | calm, confident, measured, low-pressure | hard-sell urgency | Every word should feel deliberate and expensive.",
      "urgent retail | sale, event, limited-time offer | bright, quick, clear, energetic | sensitive categories or complex disclaimers | Move fast but keep prices and dates intelligible.",
      "comic character | comedy, dialogue, memorable brand devices | specific, playful, reactive, timed | regulated claims or serious topics | Play the situation, not a cartoon voice.",
      "cinematic narrator | launches, trailers, high-impact promos | big, controlled, spacious, dramatic | simple local offers | Create scale but do not swamp the product message.",
      "youthful social | events, youth brands, digital audio | relaxed, current, casual, quick | financial or medical authority | Keep it real and unscripted, but still clear."
    ],
    "keywords": [
      "voice style use case table",
      "voice",
      "casting",
      "style",
      "Voice Style Use Case Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/voice_style_use_case_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:sfx_type_use_case_table",
    "title": "Sfx Type Use Case Table",
    "topic": "sfx_type_use_case_table",
    "productionStage": [
      "sound_design"
    ],
    "appliesTo": [
      "radio",
      "sfx"
    ],
    "summary": "Operational lookup table imported from tables/sfx_type_use_case_table.csv.",
    "guidance": [
      "whoosh | transitions, price reveals | Short and lower than VO | Overuse feels dated | Soft whoosh into offer line.",
      "riser | countdowns, launches, urgency | Build under music, duck before VO | Can create clutter | Two-second rise into brand reveal.",
      "impact | logo sting, punchline, proof moment | Place after or before speech, not over key words | Can feel aggressive | Low impact after “half price”.",
      "ambience | scene-setting and localization | Keep wide but mono-safe | Masks low-level VO | Gentle cafe bed under first three seconds.",
      "product sound | food, automotive, retail proof | Use as evidence, close and clean | Unrealistic foley harms trust | Crisp can open before product line.",
      "comedy hit | jokes, reversals | Use sparingly and time to reaction | Can cheapen premium tone | Tiny rimshot after awkward pause."
    ],
    "keywords": [
      "sfx type use case table",
      "sfx",
      "sound design",
      "foley",
      "Sfx Type Use Case Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/sfx_type_use_case_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:music_mood_bpm_table",
    "title": "Music Mood Bpm Table",
    "topic": "music_mood_bpm_table",
    "productionStage": [
      "music"
    ],
    "appliesTo": [
      "radio",
      "music",
      "digital"
    ],
    "summary": "Operational lookup table imported from tables/music_mood_bpm_table.csv.",
    "guidance": [
      "calm trust | 70-90 | ambient, acoustic, soft piano | healthcare, public service, finance | Leave room for thoughtful pauses.",
      "confident premium | 85-110 | minimal electronic, cinematic pulses | luxury, automotive, corporate | Avoid busy toplines under VO.",
      "bright retail | 115-140 | pop, indie, upbeat acoustic | sales, openings, family retail | Use clear downbeats for price reveals.",
      "urgent event | 130-160 | electronic, rock, trailer percussion | limited-time offers, concerts | Build tension but protect words.",
      "warm local | 90-120 | folk, light soul, organic textures | Irish/UK local services | Sound human rather than stock.",
      "comedy quirky | 95-140 | plucked strings, novelty percussion | character spots, reversals | Let the joke breathe; avoid constant mickey-mousing."
    ],
    "keywords": [
      "music mood bpm table",
      "music",
      "score",
      "bpm",
      "mood",
      "Music Mood Bpm Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/music_mood_bpm_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:script_problem_fix_table",
    "title": "Script Problem Fix Table",
    "topic": "script_problem_fix_table",
    "productionStage": [
      "script"
    ],
    "appliesTo": [
      "radio",
      "digital"
    ],
    "summary": "Operational lookup table imported from tables/script_problem_fix_table.csv.",
    "guidance": [
      "too many messages | listener cannot retell offer | choose one core action | Great prices, new ranges, expert staff, online booking and parking. | Book your free fitting today, with expert staff and easy parking.",
      "weak opening | first line is generic | start with listener problem or vivid scene | Looking for great value? | Your boiler always knows when guests are coming.",
      "buried brand | brand appears only at end | name brand early and late | Sale now on in store. | The Murphy Motors Summer Sale is now on.",
      "legal tag too fast | disclaimer rushed and unsafe | shorten claim or move detail online | Finance from 0%, terms apply, subject to status... | 0% finance available, subject to status. Full terms online.",
      "weak CTA | no action or time frame | use concrete action and deadline | Visit us soon. | Book by Friday at napkinaudio.ie."
    ],
    "keywords": [
      "script problem fix table",
      "script",
      "copy",
      "fix",
      "Script Problem Fix Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/script_problem_fix_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:client_feedback_translation_table",
    "title": "Client Feedback Translation Table",
    "topic": "client_feedback_translation_table",
    "productionStage": [
      "brief",
      "script"
    ],
    "appliesTo": [
      "radio",
      "digital"
    ],
    "summary": "Operational lookup table imported from tables/client_feedback_translation_table.csv.",
    "guidance": [
      "Make it pop | Needs more contrast or energy | Which moment should stand out? | Lift hook, add transition impact, brighten music, tighten pauses.",
      "More premium | Less shouty, more spacious, higher craft | Premium in voice, music, or mix? | Lower pace, reduce hype words, choose sparse bed, soften limiter.",
      "Less salesy | Feels pushy or over-claimed | Which line feels too hard sell? | Remove clichés, use proof, make CTA calmer, conversational VO.",
      "More energy | Pacing feels slow | Should energy come from read or track? | Increase tempo, shorten copy, add lift before CTA.",
      "Too shouty | VO is too loud/urgent/bright | Is it the performance or mix level? | Recast/redirect softer, reduce presence, lower VO 1 dB.",
      "Too flat | No emotional shape | Where should it build? | Regenerate VO, mark emphasis, add music arc and SFX beats."
    ],
    "keywords": [
      "client feedback translation table",
      "client feedback",
      "translation",
      "revision",
      "Client Feedback Translation Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/client_feedback_translation_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:compliance_risk_flags_table",
    "title": "Compliance Risk Flags Table",
    "topic": "compliance_risk_flags_table",
    "productionStage": [
      "compliance",
      "export"
    ],
    "appliesTo": [
      "radio",
      "digital"
    ],
    "summary": "Operational lookup table imported from tables/compliance_risk_flags_table.csv.",
    "guidance": [
      "alcohol | Appeals to under-18s, irresponsible consumption, health/social success claims | Flag social responsibility and age-targeting risk. | Always for broadcast alcohol copy.",
      "gambling | Urgency, financial rescue, under-18 appeal, vulnerable targeting | Flag BCAP gambling risk and ask for clearance evidence. | Always.",
      "finance | Rates, credit, investments, savings, risk claims | Ask for substantiation and regulated wording. | Always.",
      "health/medical | Treatment, cure, diagnosis, professional endorsement | Avoid medical advice; request evidence and legal review. | Always.",
      "children | Direct exhortation, pester power, unsafe behaviour | Flag child-protection rules. | Always if child-directed.",
      "environmental | Green, sustainable, carbon-neutral, eco claims | Ask for lifecycle evidence and precise wording. | Always for comparative/absolute claims."
    ],
    "keywords": [
      "compliance risk flags table",
      "compliance",
      "risk",
      "legal",
      "Compliance Risk Flags Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/compliance_risk_flags_table.csv",
    "reliability": "imported"
  },
  {
    "id": "napkin-audio:table:final_export_qa_table",
    "title": "Final Export Qa Table",
    "topic": "final_export_qa_table",
    "productionStage": [
      "export",
      "compliance"
    ],
    "appliesTo": [
      "radio",
      "digital"
    ],
    "summary": "Operational lookup table imported from tables/final_export_qa_table.csv.",
    "guidance": [
      "duration | Ends within booked slot, including required silence/sting | DAW timeline and bounce length | Trim copy or music tail.",
      "loudness | Matches destination LUFS/LKFS | ITU BS.1770 loudness meter | Normalize or remaster.",
      "true peak | At or below destination ceiling | True-peak meter | Lower limiter ceiling and re-export.",
      "format | Correct WAV/MP3/AAC, sample rate, bit depth/bitrate | Export settings check | Re-export from master.",
      "mono compatibility | No disappearing VO/SFX | Mono fold-down listen | Center critical elements, fix phase.",
      "intelligibility | Offer, brand, CTA understood after one listen | Phone/car/smart speaker check | Duck music, simplify SFX, revise copy."
    ],
    "keywords": [
      "final export qa table",
      "export",
      "qa",
      "delivery",
      "Final Export Qa Table"
    ],
    "source": "Napkin Audio AI Studio RAG Knowledge Dataset 1.0.0: tables/final_export_qa_table.csv",
    "reliability": "imported"
  }
];
